
mode = { raw-speed = { space = 128 } }
concurrency = 1000
duration = { iters = 10000 }
chain = "https://api.devnet.solana.com/"
ephem = "https://devnet.magicblock.app/"
ws = "wss://devnet.magicblock.app"
keypairs = ["/users/babur/bencher.json"]
