sigverify = true
# mode = { raw-speed = { space = 512, local = false } }
mode = { clone-speed = { noise = 16 } }
concurrency = 50
latency = 100
duration = { iters = 1000 }
chain = "https://api.devnet.solana.com/"
ephem = "http://0.0.0.0:8899"
# ephem = "http://0.0.0.0:7799"
# ephem = "https://devnet.magicblock.app"
ws = "ws://0.0.0.0:8900"
# ws = "ws://0.0.0.0:7800"
# ws = "wss://devnet.magicblock.app"
keypairs = ["/users/babur/bencher.json"]
subscriptions = true
confirmations = true
validator-mode = "ephemeral"
