modes = [
	{ raw-speed = { space = 128 } }, 
	# { clone-speed = { noise = 2 } }, 
	# { clone-speed = { noise = 8 } }, 
	# { clone-speed = { noise = 16 } }, 
]
concurrency = [16]
duration = { iters = 5000}
chain = "https://rpc.magicblock.app/devnet"
ephem = "http://0.0.0.0:8899"
# ephem = "http://0.0.0.0:8080"
# ephem = "https://devnet.magicblock.app"
ws = "ws://0.0.0.0:8900"
# ws = "ws://0.0.0.0:8080"
# ws = "wss://devnet.magicblock.app"
keypairs = ["payer.json"]
